# This is a basic workflow to help you get started with Actions

name: creating documentation
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Doxygenize
      # You may pin to the exact commit or the version.
      uses: langroodi/doxygenize@v1.7
      # uses: pviscone/doxygenize@v1.6.3
      with:
        # Doxygen configuration file path
        doxygenconf: ./docs/Doxyfile
        # Generated HTML documents output folder forse ci devo aggiungere ./html
        htmloutput: ./html/
        # GitHub Pages branch name
        ghpagesbranch: gh-pages
        # GitHub Pages directory path
        ghpagesdir: ./html/
